#!/bin/bash
echo -e "\033[33mPWD: `pwd`\033[0m"
echo -e "\033[32mSTR: run git hook\033[0m"

echo -e "==>Step 1: update README.md"
java -jar hooks/pre-commit.jar
echo -e "==>Step 2: git add README.md"
git add README.md

echo -e "\033[32mEND: run git hook\033[0m\n"
